### ISSUE TITLE
0.1.3 breaks functionality for querying for cloudcover intervals

### ISSUE THREAD

**Issue by subnet001** [SDFIdk/CDSETool#30]
## Describe the bug
In cdsetool 0.1.2 cloudCover (and probably other things queried for in lists) could be queried for via

```python
"cloudCover": '[0, 70]'
```

This no longer functions in 0.1.3. 
If the method for querying has been updated, readme should include working example.

### Steps to reproduce
```python

    from cdsetool.query import query_features

    features = query_features(
        "Sentinel2",
        {
            "startDate": "2020-10-20",
            "completionDate": "2020-12-20",
            "box": ["4","51","4.5","52"],
            "processingLevel": "S2MSI2A",
            "cloudCover": '[0, 20]'           
        },
    )
    print(len(list(features)))
```
yields
```python
AssertionError: search_term [0, 70] does not match pattern ^(\[|\]|[0-9])?[0-9]+$|^[0-9]+?(\[|\])$|^(\[|\])[0-9]+,[0-9]+(\[|\])$
```

### Expected behavior
Expected to find 26 features

### Environment
Windows 10
VSCode

**Comment by pedep** [comment]
The regex mentioned in the error message is derived from the `describe.xml` document provided by [CDSE](https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel2/describe.xml).
It seems the patterns provided in this document is meant for client-side validation, since the server does not respond with error to non-matching queries

The pattern for `cloudCover` consists of 3 separate regex, joined by OR `|`
```
regex 1 ^(\[|\]|[0-9])?[0-9]+$
regex 2 ^[0-9]+?(\[|\])$
regex 3 ^(\[|\])[0-9]+,[0-9]+(\[|\])$
```

first regex will match
- `^` start of text
- `(\[|\]|[0-9])?` 0 or 1 characters matching either `[`, `]` or a single digit number
- `[0-9]+` one or more numbers
- `$` end of text

matching examples `[100`, `]60`, `20`

second regex will match
- `^` start of text
- `[0-9]+?` match as few as possible numbers
- `(\[|\])` match either `[` or `]`
- `$` end of text

third regex will match
- `^` start of text
- `(\[|\])` match either `[` or `]`
- `[0-9]+` one or more numbers
- `,` the character comma `,`
- `[0-9]+` one or more numbers
- `(\[|\])` match either `[` or `]`

Going by your examlpe, the third sub-regex would be the one you are trying to use.
`'[0, 20]'` would match, except for the ` ` space in the middle. Remove this and it works just fine

```python
import re

pattern = '^(\[|\]|[0-9])?[0-9]+$|^[0-9]+?(\[|\])$|^(\[|\])[0-9]+,[0-9]+(\[|\])$'

assert not re.match(pattern, '[0, 20]')
assert re.match(pattern, '[0,20]')
```
